### ISSUE TITLE
Icons for RetroPie menu?

### ISSUE THREAD

**Issue by AndersHP84** [mmatyas/pegasus-theme-grid-micro#1]
Is it possible somehow to add icons to the RetroPie menu?
This is the only thing that seems unfinished when browsing through the system folders.

**Comment by mmatyas** [comment]
They seem to be working fine for me. By default the RetroPie menu support comes from ES, and so the images used are what's defined in its gamelist.xml (`/home/pi/.emulationstation/gamelists/retropie/gamelist.xml`).

**Comment by mmatyas** [comment]
I guess this can be closed.
